// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ads.proto

package extra

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ads struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price                string   `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ads) Reset()         { *m = Ads{} }
func (m *Ads) String() string { return proto.CompactTextString(m) }
func (*Ads) ProtoMessage()    {}
func (*Ads) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e37b36e10f7b333, []int{0}
}

func (m *Ads) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ads.Unmarshal(m, b)
}
func (m *Ads) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ads.Marshal(b, m, deterministic)
}
func (m *Ads) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ads.Merge(m, src)
}
func (m *Ads) XXX_Size() int {
	return xxx_messageInfo_Ads.Size(m)
}
func (m *Ads) XXX_DiscardUnknown() {
	xxx_messageInfo_Ads.DiscardUnknown(m)
}

var xxx_messageInfo_Ads proto.InternalMessageInfo

func (m *Ads) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ads) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

type AdsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdsRequest) Reset()         { *m = AdsRequest{} }
func (m *AdsRequest) String() string { return proto.CompactTextString(m) }
func (*AdsRequest) ProtoMessage()    {}
func (*AdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e37b36e10f7b333, []int{1}
}

func (m *AdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdsRequest.Unmarshal(m, b)
}
func (m *AdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdsRequest.Marshal(b, m, deterministic)
}
func (m *AdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdsRequest.Merge(m, src)
}
func (m *AdsRequest) XXX_Size() int {
	return xxx_messageInfo_AdsRequest.Size(m)
}
func (m *AdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdsRequest proto.InternalMessageInfo

func (m *AdsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AdsResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdsResponse) Reset()         { *m = AdsResponse{} }
func (m *AdsResponse) String() string { return proto.CompactTextString(m) }
func (*AdsResponse) ProtoMessage()    {}
func (*AdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e37b36e10f7b333, []int{2}
}

func (m *AdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdsResponse.Unmarshal(m, b)
}
func (m *AdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdsResponse.Marshal(b, m, deterministic)
}
func (m *AdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdsResponse.Merge(m, src)
}
func (m *AdsResponse) XXX_Size() int {
	return xxx_messageInfo_AdsResponse.Size(m)
}
func (m *AdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdsResponse proto.InternalMessageInfo

func (m *AdsResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Ads)(nil), "powermock.extra.Ads")
	proto.RegisterType((*AdsRequest)(nil), "powermock.extra.AdsRequest")
	proto.RegisterType((*AdsResponse)(nil), "powermock.extra.AdsResponse")
}

func init() { proto.RegisterFile("ads.proto", fileDescriptor_6e37b36e10f7b333) }

var fileDescriptor_6e37b36e10f7b333 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x4c, 0x29, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2f, 0xc8, 0x2f, 0x4f, 0x2d, 0xca, 0xcd, 0x4f, 0xce,
	0xd6, 0x4b, 0xad, 0x28, 0x29, 0x4a, 0x54, 0xd2, 0xe7, 0x62, 0x76, 0x4c, 0x29, 0x16, 0x12, 0xe2,
	0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x44,
	0xb8, 0x58, 0x0b, 0x8a, 0x32, 0x93, 0x53, 0x25, 0x98, 0xc0, 0x82, 0x10, 0x8e, 0x92, 0x0c, 0x17,
	0x97, 0x63, 0x4a, 0x71, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x10, 0x1f, 0x17, 0x53, 0x66,
	0x0a, 0x54, 0x17, 0x53, 0x66, 0x8a, 0x92, 0x22, 0x17, 0x37, 0x58, 0xb6, 0xb8, 0x20, 0x3f, 0xaf,
	0x38, 0x15, 0x64, 0x6c, 0x4a, 0x62, 0x49, 0x22, 0xcc, 0x58, 0x10, 0xdb, 0xc8, 0x0f, 0x6c, 0x40,
	0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x03, 0xc4, 0x7e, 0x69, 0x3d, 0x34, 0x87, 0xe9,
	0x21, 0x2c, 0x91, 0x92, 0xc1, 0x2e, 0x09, 0xb1, 0xc3, 0x49, 0x3c, 0x4a, 0x14, 0x4d, 0xda, 0x1a,
	0x4c, 0x26, 0xb1, 0x81, 0xbd, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x94, 0x0e, 0x00, 0x4d,
	0xff, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdsServiceClient is the client API for AdsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdsServiceClient interface {
	Ads(ctx context.Context, in *AdsRequest, opts ...grpc.CallOption) (*AdsResponse, error)
}

type adsServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdsServiceClient(cc *grpc.ClientConn) AdsServiceClient {
	return &adsServiceClient{cc}
}

func (c *adsServiceClient) Ads(ctx context.Context, in *AdsRequest, opts ...grpc.CallOption) (*AdsResponse, error) {
	out := new(AdsResponse)
	err := c.cc.Invoke(ctx, "/powermock.extra.AdsService/Ads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdsServiceServer is the server API for AdsService service.
type AdsServiceServer interface {
	Ads(context.Context, *AdsRequest) (*AdsResponse, error)
}

func RegisterAdsServiceServer(s *grpc.Server, srv AdsServiceServer) {
	s.RegisterService(&_AdsService_serviceDesc, srv)
}

func _AdsService_Ads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).Ads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powermock.extra.AdsService/Ads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).Ads(ctx, req.(*AdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "powermock.extra.AdsService",
	HandlerType: (*AdsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ads",
			Handler:    _AdsService_Ads_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ads.proto",
}
